# Render.com 배포를 위한 설정 파일
# 이 파일은 Node.js 백엔드 서비스와 Firestore 연동을 정의합니다.

services:
  # Node.js 백엔드 웹 서비스 정의
  - type: web # 웹 서비스 타입
    name: zre-challenge-backend # 백엔드 서비스 이름 (원하는 이름으로 변경 가능)
    env: node # 환경: Node.js
    region: singapore # 서비스 배포 지역 (사용자에게 가까운 지역으로 선택)
    buildCommand: npm install # 빌드 명령 (프로젝트에 따라 yarn install 또는 npm ci 사용 가능)
    startCommand: node server.js # 시작 명령 (백엔드 진입점 파일에 맞게 변경: 예: node index.js)
    envVars:
      # Firebase 서비스 계정 JSON 파일의 내용을 환경 변수로 설정합니다.
      # 보안을 위해 Render 대시보드에서 직접 설정하는 것을 강력히 권장합니다.
      # JSON 파일 내용을 한 줄로 만들어 여기에 붙여넣거나,
      # Render 대시보드에서 각 필드를 개별 환경 변수로 설정할 수 있습니다.
      - key: FIREBASE_CONFIG
        # value: '{ "type": "service_account", "project_id": "your-project-id", ... }'
        # 위 주석 처리된 라인 대신, 실제 서비스 계정 JSON 내용을 한 줄로 붙여넣으세요.
        # 또는 Render 대시보드에서 직접 환경 변수를 추가하세요.
        # 예시:
        # key: FIREBASE_TYPE
        # value: service_account
        # key: FIREBASE_PROJECT_ID
        # value: your-project-id
        # ... (나머지 필드도 동일하게)
        # 이 경우, server.js에서 process.env.FIREBASE_TYPE 등으로 개별 필드를 읽어야 합니다.
        # 가장 간단한 방법은 전체 JSON을 FIREBASE_CONFIG에 넣는 것입니다.
        generateValue: false # Render가 자동으로 값을 생성하지 않도록 설정

      # JWT 토큰 서명에 사용할 비밀 키 (필수)
      - key: JWT_SECRET
        generateValue: true # Render가 자동으로 안전한 값을 생성하도록 합니다.
        # 또는 직접 값을 설정할 수도 있습니다: value: "your_super_secret_jwt_key"
      
      # Node.js 앱이 리스닝할 포트. Render가 자동으로 주입하므로 보통 명시할 필요는 없지만, 명시적으로 설정할 경우.
      - key: PORT
        value: 10000 # Render는 기본적으로 10000 포트를 사용합니다.

    # pullRequestPreviews:
    #   autoDeploy: true

    # autoDeploy: true # Git 저장소에 푸시될 때마다 자동 배포할지 여부
